NOTIFICATION_EMAIL = "email"
NOTIFICATION_SMS = "sms"
NOTIFICATION_PUSH = "push"
STATUS_QUEUED = "queued"
STATUS_PROCESSING = "processing"
STATUS_SENT = "sent"
STATUS_FAILED = "failed"

NOTIFICATION_TYPES: list[str] = [
    NOTIFICATION_EMAIL,
    NOTIFICATION_SMS,
    NOTIFICATION_PUSH,
]

STATUSES: list[str] = [STATUS_QUEUED, STATUS_PROCESSING, STATUS_SENT, STATUS_FAILED]
